config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get 'about', to: 'pages#about'
  resources :recipes, only: [:index, :new, :create]
  resources :tags, only: [:index, :show], param: :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  include PgSearch
  has_many :taggings
  has_many :tags, through: :taggings
  validates :name, presence: true
  validates :instructions, presence: true
  pg_search_scope :search, against: [:name, :instructions]
  serialize :ingredients, JSON
  paginates_per 50

  def ingredients_list
    ingredients.map { |i| i["string"] } if ingredients.any?
  end

  def ingredients_list=(input)
    self.ingredients = IngredientsParser.parse(input)
  end

  def tag_names
    tags.map(&:name).join(", ")
  end

  def tag_names=(names)
    self.tags = names.split(",").map do |name|
      t = Tag.where(name: name.strip).first_or_create!
      t.count += 1
      t
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :recipes, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    if params[:query].present?
      @recipes = Recipe.search(params[:query]).page(params[:page]).per(5)
    else
      @recipes = Recipe.all.page(params[:page]).per(5)
    end
  end

  def new
    @recipe = Recipe.new
    @popular_tags = Tag.order(count: :desc).first(5)
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:success] = "Recipe saved"
      redirect_to recipes_path
    else
      flash[:danger] =  @recipe.errors.full_messages.join(", ")
      render :new
    end
  end

  private
    def recipe_params
       raw_params = params.require(:recipe).permit(:name, :instructions, :ingredients_list, :tag_names)
       raw_params
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
    @sum = @tags.inject(0) { |sum, tag| sum + tag.count}
  end

  def show
    if tag
      @recipes = tag.recipes.page(params[:page]).per(5)
    else
      @recipes = Recipe.none.page(params[:page]).per(5)
    end
    render 'recipes/index'
  end

  private

  def tag
    if params[:name].present?
      Tag.find_by_name(params[:name])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Escumoire</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,800" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-cutlery"></i>
            Escumoire
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= form_tag recipes_path, class: "navbar-form", method: "get", enforce_utf8: false do %>
                <div class="input-group">
                  <%= text_field_tag :query, params[:query], class: "form-control" %>
                  <div class="input-group-btn">
                    <%= button_tag(class: "btn btn-default", name: nil) do %>
                      <%= content_tag("i", nil, class: "fa fa-search") %>
                    <% end %>
                  </div>
                </div>
              <% end %>
              <!-- <form class="navbar-form" action='/recipes' method="get">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search" name="query" id="query">
                  <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </form> -->
            </li>
            <li><%= link_to "Recipes", recipes_path %> </li>
            <li><%= link_to "About", "https://www.youtube.com/watch?v=dQw4w9WgXcQ" %> </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <div class="container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, class: "alert alert-#{type}" do %>
          <%= msg %>
          <button class="close" data-dismiss="alert">×</button>
        <% end %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
Hi

app/views/pages/index.html.erb
<div class ="home_title container-fluid text-center ">
<h1>Welcome to Escumoire</h1>
<h3>Let's share some magic flavors, yo!</h3>
<%= link_to "Submit your recipe", new_recipe_path, class: "add_recipe_btn btn btn-primary btn-lg text-center" %>
</div>

app/views/recipes/_recipe.html.erb
<div class="well col-lg-8">

  <h1> <%= recipe.name %> </h1>
  <h3> Способ приготовления: </h3>
  <p>
    <%= simple_format recipe.instructions %>
  </p>
  <h3> Ингредиенты: </h3>
  <p>
    <ul class="list-group">
    <% if recipe.ingredients_list %>
      <% recipe.ingredients_list.each do |ingredient| %>
        <li class="list-group-item"><%= ingredient %> </li>
      <% end %>
    <% end %>
    </ul>
  </p>
  <h3> Тэги: </h3>
  <p>
    <%= raw recipe.tags.map { |tag| link_to tag.name, '/tags/' + tag.name }.join(", ") %>
  </p>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <% @recipes.each do |recipe| %>
    <div class="row">
      <%= render partial: 'recipes/recipe', object: recipe %>
    </div>
  <% end %>
  <%= paginate @recipes, :theme => 'twitter-bootstrap-3' %>
</div>

app/views/recipes/new.html.erb
<script type="text/javascript">
  $(document).ready(new_recipe_page);
  $(document).on('page:change', new_recipe_page);
</script>
<div class="container">
  <div class="row vtop">
    <h3 class="text-center"> Insert your recipe </h3>
    <div class="col-md-8 col-md-offset-2">
      <div class="well">
        <%= form_for @recipe do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'name-field form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :instructions %>
            <%= f.text_area :instructions, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :ingredients %>
            <%= f.text_area :ingredients_list, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :tag_names %>
            <%= f.text_field :tag_names, class: 'form-control', id: 'tagsinput'%>
            <div id="populartags" class="container">
              <% @popular_tags.each do |tag| %>
                <%= content_tag :span, tag.name, class: "populartag" %>
              <% end %>
            </div>
          </div>
          <%= f.submit 'Submit', class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tags/index.html.erb
<script type="text/javascript">
  $(document).ready(tags_page);
  $(document).on('page:change', tags_page);
</script>
<div class="container">
  <div id="tagcloud">
    <% @tags.each do |tag| %>
      <%= link_to tag.name, '/tags/' + tag.name, rel: ( (tag.count*100 / @sum) ).to_s %>
    <% end %>
  </div>
</div>